[k8s-master]
master ansible_host=172.17.91.131 ansible_port=22 ansible_user=centos ansible_ssh_private_key_file=/home/centos/.ssh/kadalipp

[k8s-workers]
worker1 ansible_host=172.17.90.20 ansible_port=22 ansible_user=centos ansible_ssh_private_key_file=/home/centos/.ssh/kadalipp

worker2 ansible_host=172.17.88.73 ansible_port=22 ansible_user=centos ansible_ssh_private_key_file=/home/centos/.ssh/kadalipp