---
- name: create
  hosts: k8s-master
  gather_facts: true
  become: true
  become_user: centos

  tasks:
    - name: Create target directory
      file:
       path=/home/centos/deploy_nginx/
       state=directory

    - name: create the deployment file
      lineinfile:
            path: /home/centos/deploy_nginx/deploy1.yaml
            create: yes
            line: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: nginx-deployment
                labels:
                  app: nginx
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: nginx
                template:
                  metadata:
                    labels:
                      app: nginx
                  spec:
                    containers:
                    - name: nginx
                      image: nginx:1.14.0
                      ports:
                      - containerPort: 80
    - name: create the deployment by running the kubectl command
      command: "kubectl create -f /home/centos/deploy_nginx/deploy1.yaml"

    - name: create the service file
      lineinfile:
            path: /home/centos/deploy_nginx/service1.yaml
            create: yes
            line: |
              apiVersion: v1
              kind: Service
              metadata:
                    name: nginx-service
                    labels:
                      run: nginx-service
              spec:
                    type: NodePort
                    ports:
                    - port: 80
                      protocol: TCP
                    selector:
                      app: nginx
    - name: create the service
      command: "kubectl create -f /home/centos/deploy_nginx/service1.yaml"
