deploy:
  stage: deploy
  image:
     name: bitnami/kubectl:latest
     entrypoint: [""]
  script:
    - kubectl config get-contexts
    - kubectl config use-context devops2022-fall/students/devops2022Fall-Kadalipp-B75914/lab05-flask-microservice:microservice
    - kubectl config current-context
    - kubectl get pods
    - kubectl delete -f ./deployment.yaml || true
    - kubectl apply -f ./deployment.yaml
