---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vclaim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    app: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: gitlab.cs.ut.ee:5050/devops2022-fall/students/devops2022fall-kadalipp-b75914/lab07-gitlab-cicd/lab07:25990
        ports:
        - containerPort: 5000
        lifecycle:
          postStart:
            exec:
              command: ["cp", "/data/CO2.csv", "/app/CO2.csv"] 
        volumeMounts:
          - mountPath: "/data"
            name: data-storage-volume
      imagePullSecrets:
      - name: registry-credentials
      volumes:
      - name: data-storage-volume
        persistentVolumeClaim:
          claimName: vclaim
---
apiVersion: v1
kind: Service
metadata:
  name: service-flaskapp
spec:
  type: NodePort
  selector:
    app: flaskapp
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: tcp-80
